### ISSUE TITLE
QG4 System Team checks (Release 3.1)

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sldt-semantic-hub#101]
# QG checks

## Please keep this issue open until QG4 is concluded!

Product Name: Semantic Hub
Product Owner: Thomas Henn
Dev SPOC: Lukas Römer, Tunahan Cicek
Helm Chart Version: <s>`0.1.16`</s> → `0.1.19`
App Version: <s>`0.2.4-M1`</s> → `0.2.6-M1`
QG4 Approval: no

##### TRG 1.01
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1
- [x] an appropriate `README.md` file
###### TRG 1.02
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2
- [ ] an appropriate `INSTALL.md`
###### TRG 1.03
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3
- [x] #106
  - [x] the versioning itself follows [semantic versioning](https://semver.org/)
##### TRG 2.01
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1
- [x] default branch is named `main`
##### TRG 2.03
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3
- [x] `/docs` directory
- [x] must contain detailed product related documentation for the Tractus-X product
- [x] `/charts` directory
- [x] must contain the Helm chart for the Tractus-X product IF available
- [x] `AUTHORS.md` file (optional)
- [x] `CODE_OF_CONDUCT.md` file
- [x] `CONTRIBUTING.md` file
- [x] #105
- [x] run Dash tool to compare
- [x] `LICENSE` file
- [x] `NOTICE.md` file
- [x] `SECURITY.md` file
##### TRG 2.04
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4
- [x] a Leading product repository
- [x] repository name must be _productname_ without prefix or suffix
- [x] should contain the release
- [x] references/urls to the product's other repositories
- [x] might contain product helm chart
- [x] README.md: contains the urls for the backend and frontend applications
- [x] Links to Repository
- [x] Does it reference all other repositories?
- [x] Does it contain the Product Helm chart?
##### TRG 2.05
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5
- [x] #107
- [ ] file has a proper format
##### TRG 3.02
https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2
- [x] if data persistence is needed in Kubernetes the use of PersistentVolume and PersistentVolumeClaim resource
##### TRG 4.01
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-1
- [x] All images must be tagged following [semantic versioning](https://semver.org/)
- [x] #112
##### TRG 4.02
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-2
- [x] must add a section to your top level `README.md` file, that contains information about the used base image
- [x] Java, Kotlin, ... if JVM based language use base image from [Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin)
##### TRG 4.03
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-3
- [x] image has `USER` command to specify a non-root user to run the container
- [x] `deployment.yaml` has `runAsUser` and `allowPrivilegeEscalation: false` properly set
##### TRG 4.05
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-5
- [x] released image must be present on `GitHub Package registry` or `Dockerhub`
##### TRG 5.01
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01
- [x] Helm chart must be released
- [x] appropriate semantic versioning for `version` and `appVersion` has to be used in `Chart.yaml`
- [x] must not contain any environment specific `values-xyz.yaml`
- [x] `values.yaml` file must contain proper default values/placeholders
- [x] No hostname provided for ingress
- [x] Ingress is disabled
- [x] No references to any secret engine service (e.g.: Hashicorp Vault)
- [x] Dependencies should be prefixed with the nameOverride and/or fullnameOverride properties
- [x] Image tag is set to the `Chart.yaml` `appVersion` property
- [x] must be deployable to any environment without overwriting default values with a simple helm install command
- [x] dependencies have to be declared in Chart.yaml NOT requirements.yml
- [x] recommended use GitHub [Chart Releaser Action](https://github.com/helm/chart-releaser-action)
##### TRG 5.02
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02
- [x] Helm chart location inside Git repository in `/charts` directory
- [x] chart file structure
``` markdown
charts/ 
    chartNameA/
      Chart.yaml
      ... 
    chartNameB/
      Chart.yaml
      ...
AUTHORS.md 
DEPENDENCIES.md 
LICENCE 
README.md 
```
- [x] #108
- [x] latest tag is not used in helm chart be default
##### TRG 5.04
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04
- [x] CPU and memory limits and requests are properly set
##### TRG 5.06
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06
- [x] every startup configuration aspect of your application must be configurable through the Helm chart (ingress class, tls, labels, annotations, database, secrets, persistence, env variables)
##### TRG 5.07
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07
- [x] if dependencies are present in the `Chart.yaml` they are properly configured
##### TRG 5.08
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08
- [x] a product has a single deployable helm chart that contains all components (backend, frontend, etc.)
- [x] name of the Chart should be just the product-name without prefix or suffix
- [x] values file should contain all available variables (even from subcharts) with default values and comments about what they do
- [x] helm install command should successfully install the chart to any supported Kubernetes version cluster (without overwriting default values)
- [ ] helm test runs without errors

#### Testing
- [ ] installed and running on pre-prod without errors

**Comment by almadigabor** [comment]
Hi Semantic Hub Team! I would kindly ask you to fill these information:

```
Product Owner:
Dev SPOC:
Helm Chart Version:
App Version:
```

**Comment by tunacicek** [comment]
Hi Gabor,
sure. 

Product Owner: Thomas Henn
Dev SPOC: Lukas Römer, Tunahan Cicek
Helm Chart Version: 0.1.16
App Version: 0.2.4-M1

**Comment by carslen** [comment]
## Section TRG 1
✅ TRG 1.01 `README.md`
✅ TRG 1.02 `INSTALL.md` is optional and `README.md` contains sufficient install instructions.
❌ TRG 1.03 `CHANGELOG.md` Released version missing → #106

**Comment by carslen** [comment]
## Section TRG 2
✅ TRG 2.01 Default Branch main
❌ TRG 2.03 Repo Structure → #105 
✅ TRG 2.04 Leading Product Repo
⚠️ TRG 2.05 Repository metafile #107 (non blocking issue)

**Comment by carslen** [comment]
## Section TRG 3
✅ TRG 3.02 - Persist Data

**Comment by carslen** [comment]
## Section TRG 4
⚠️ TRG 4.01 Image tagging (SemVer versioned, but latest tag on newest image tag is missing. Also not following suggestion of TRG at all in regards of tagging, eg `0`, `0.1`, `0.1.2`.) Non blocking
✅ TRG 4.02 Base Image
✅ TRG 4.03 Non root container
✅ TRG 4.05 Container Registries

**Comment by carslen** [comment]
Still in progress to clarify how to fix problems (#105 #106 #108). I'll keep you posted.

**Comment by carslen** [comment]
Final feedback: A bugfix release is OK as long no technical changes are implemented. Therefor I ask you to work on #105, #106 and #108 and create a new release (application and Helm chart).

**Comment by carslen** [comment]
Is there any update? Do you need support? @tunacicek @LuLeRoemer

**Comment by bs-jokri** [comment]
Hi @carslen,
thanks for your feedback. We worked on the issues
https://github.com/eclipse-tractusx/sldt-semantic-hub/issues/105
https://github.com/eclipse-tractusx/sldt-semantic-hub/issues/106
https://github.com/eclipse-tractusx/sldt-semantic-hub/issues/108

and fixed the identified issues.

The new release can be found here: https://github.com/eclipse-tractusx/sldt-semantic-hub/releases/tag/v0.2.6-M1

Ok for you? If so it would be great to approve the QG4 criteria.

**Comment by carslen** [comment]
Great! I've already reported the new version (0.2.6-M1 and 0.1.19 for the Helm Chart) to release management to be part of Release 3.1.

There are still some minor issues (#107 #112) open, but they don't block.

**Comment by bs-jokri** [comment]
@carslen thank you.
