### ISSUE TITLE
`Changelog.md`

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/sldt-semantic-hub#106]
Released version 0.2.4-M1 is missing in  `Changelog.md`.

Issue identified while working on #101.

**Comment by tunacicek** [comment]
@carslen The version should be available in the changelog.md. 

![Screenshot 2023-04-26 at 11 20 47](https://user-images.githubusercontent.com/115143031/234531658-40bb7d31-1c43-4b63-ade3-14e8f183dedd.png)

**Comment by carslen** [comment]
In `main` branch, but not in the release [0.2.4-M1](https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/v0.2.4-M1/CHANGELOG.md).

**Comment by LuLeRoemer** [comment]
Done

**Comment by carslen** [comment]
Solved with #109
