### ISSUE TITLE
each file must contain the Apache 2.0 Licence

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/sldt-semantic-hub#108]
- [x] Please add licence file to chart. → [TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02#chart-file-structure)

- [x] Please also ensure to update date in licence/copyright header if file has changed this year. Example:

https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/3445df1f95aa9ceefb00647b391039dd85432374/charts/semantic-hub/values.yaml#L2-L3

- [x] Also missing license header found: 

https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/3445df1f95aa9ceefb00647b391039dd85432374/charts/semantic-hub/Chart.yaml#L1-L3

- [ ] Please add [README.md](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02#the-readmemd-file) to chart, [helm-docs](https://github.com/norwoodj/helm-docs#helm-docs) might help generating this file.

**Comment by carslen** [comment]
License/Copyright header has been added with PR #74 

Unfortunately, the range of years is [not correct](https://www.eclipse.org/projects/handbook/#ip-copyright-headers), is `2021-2022` should be `2021, 2023` instead.

**Comment by carslen** [comment]
`README.md` has not been added to Helm chart with #109 , although I requested changes to this PR and mentioned to add it.

**Comment by LuLeRoemer** [comment]
Helm chart documentation is part of the global `README.md`

**Comment by carslen** [comment]
[TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02#chart-file-structure) requires a `README.md` file to be part of the released Helm Chart. The global README.md is not part of the Helm Chart.

Please add missing file to the Chart.
