### ISSUE TITLE
500 on models/{urn} when not url-encoded

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sldt-semantic-hub#116]
The following request returns an internal server error.

```
curl --location 'https://semantics.int.demo.catena-x.net/hub/api/v1/models/urn:bamm:io.catenax.material_for_recycling:1.1.0#MaterialForRecycling' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer mysecrettoken
```

Not serving the request is correct behaviour since the special characters in the url must be encoded. It should however be a 4xx.

**Comment by agg3fe** [comment]
Hi,
Thanks for reporting this. We will check this.

**Comment by tunacicek** [comment]
Done. Issue will be closed.
