### ISSUE TITLE
Improve getModelDiagram API (/models/{urn}/diagram) as it takes 4-12s response time. 

### ISSUE THREAD

**Issue by richaashara** [eclipse-tractusx/sldt-semantic-hub#130]
Response time for **API /models/{urn}/diagram**  is between 4 to 12s for 1 request and If we do 3-4 parallel request the application crashes. I have used 1 CPU and 1 GB RAM.

As, this api generates diagram on each request. To generate diagram from model text is heavy process rather than generating diagram stream on each request. We can generate a diagram file and save it with name same as URN to serve request.

On saving and updating model API call, we can invoke a thread to generate the diagram file and save it in a cloud storage or in mounted volume. While in getModelDiagram API call, we can read model file and convert into bytes array to return the response.

This can reduce getModelDiagram response time to less than 1s.
 
Please suggest which storage option for diagram file would be good, mounted volume or cloud storage like Azure BLOB?

**Comment by richaashara** [comment]
@thomas-henn , 

There are 2 suggestion we can take any of them.

1. We can generate the model diagram while we generate other formats of Semantic models in gen folder using generate.sh script execution and While get diagram API will be invoked then we just render that diagram file from the semantic model repository.

2. We can generate model diagram in POST or PUT API for saving or updating models and save it in a folder and in GET diagram API we render that stored file.

**Comment by thomas-henn** [comment]
@richaashara : We think that the first proposal with having svg-file generated and ready before API call is the most beneficial.
When should this svg generated? -- Once and therefore keep this in the gen-folder in the repository. Or, and that is most probably the better solution, generate this in the Semantic Hub and re-render this from time to time, to be up-to-date and respond to changes.

**Comment by richaashara** [comment]
@thomas-henn ,

I believe  the 1st option you mentioned seems better to me. generate svg file in gen folder with other files. 
The 2nd option you are mentioning, could you please let me know when we should generate or the svg if we do it in semantic hub? As I could only think of generating it in POST or PUT API of semantic model.

**Comment by tunacicek** [comment]
Done. The download format is now svg. Issue will be closed.
