### ISSUE TITLE
Update esmf-sdk version

### ISSUE THREAD

**Issue by richaashara** [eclipse-tractusx/sldt-semantic-hub#138]
- update esmf-sdk version to 2.2.3

**Comment by richaashara** [comment]
PR:[139](https://github.com/eclipse-tractusx/sldt-semantic-hub/pull/139) will close this issue.

**Comment by tunacicek** [comment]
Hi @richaashara ,

thanks for your feedback and PR. We will take a look over the PR.

**Comment by shijinrajbosch** [comment]
Hi @richaashara ,

Thanks for the PR. This PR is incomplete since unit tests are failing.

We are also working on ESMF SDK vesion update.

**Comment by tunacicek** [comment]
Updated to 2.4.2. Issue will be closed.
