### ISSUE TITLE
After upgrading semantic hub version from 0.1.19 to 0.1.22 GET /models returns empty response though BAMM models already exists.

### ISSUE THREAD

**Issue by richaashara** [eclipse-tractusx/sldt-semantic-hub#140]
I have updated semantic hub version in my machine to 0.1.22 and I already had existing models stored in my database. After updating version, If I am running the application, I am not getting any models in the models listing API response.

**Comment by tunacicek** [comment]
Hi @richaashara ,

This is a known bug and we are currently working to fix it.
The problem occurs because the namespace is changed with samm.

**Comment by tunacicek** [comment]
With the newest version 0.1.23 the issue solved. 
It is possible to return bamm and samm models.
