### ISSUE TITLE
TRG 7.02 License and copyright header

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sldt-semantic-hub#162]
Based on [this TRG](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02#description) check if any of these files currently missing license headers needs one:

- .github/actions/generate-dependencies-notice/package-lock.json
- .github/actions/generate-dependencies-notice/package.json
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/AspectModelNotFoundException.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/AspectModelService.java
- backend/src/main/java/org/eclipse/tractusx/semantics/hub/ModelPackageNotFoundException.java
- backend/src/main/resources/catena-template.css
- backend/src/main/resources/static/semantic-hub-openapi.yaml
- backend/src/test/resources/aas/aasJSONFormat.json
- charts/chart-testing-config.yaml
- charts/semantic-hub/config/default-realm-import.json
- pom.xml

**Comment by shijinrajbosch** [comment]
Hi @almadigabor,

It looks like JSON standards does not allow comments as additional logic to to exclude the License and copyright header comments while parsing. 
Please request you to advise if we can proceed with adding License and copyright header in the files except JSON files Or any other suggestions.

**Comment by almadigabor** [comment]
Hi @shijinrajbosch! You can proceed as you mentioned without the JSON files.

**Comment by agg3fe** [comment]
Hi @almadigabor, changes are merged into main branch. Thanks

**Comment by almadigabor** [comment]
Thanks, closing the issue.
