### ISSUE TITLE
TRG 2.03 `DEPENDENCIES` file(s) with up to date content (Dash tool generated) (TRG 2.03)

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sldt-semantic-hub#163]
Dependencies file is not up to date, please run it again with the [dash-licenses tool](https://github.com/eclipse/dash-licenses) and commit changes.

**Comment by shijinrajbosch** [comment]
Hi @almadigabor  ,

Thanks for reporting the issue. We made the required changes and merged into main branch.

**Comment by almadigabor** [comment]
Thanks, closing the issue.
