### ISSUE TITLE
docs: refenrece dockerhub image instead of ghcr

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sldt-semantic-hub#164]
Please replace the ghcr reference with the DockerHub image link [here](https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/b76892e8e9f2f286da719ebdb211408e77789786/README.md?plain=1#L101) according to the [TRG](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06#description).

**Comment by agg3fe** [comment]
Hi @almadigabor , in the latest README.md file, we have already replaced ghcr reference with the DockerHub image link. Or could you please clarify more on this what is required here if I did not understand this correctly.

**Comment by almadigabor** [comment]
Hi @agg3fe! I think you could get rid of [this line in the README](https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/8445198124fa9836af854a92dc0db08e14eba882/README.md#L45). The image will be eventually in dockerhub, that's a requirement for the release.

I've also found references here: 

- https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/8445198124fa9836af854a92dc0db08e14eba882/charts/semantic-hub/README.md#L37
- https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/8445198124fa9836af854a92dc0db08e14eba882/charts/semantic-hub/values.yaml#L73

Can you explain what this image is used for?

**Comment by agg3fe** [comment]
Hi @almadigabor,
We have raised the PR for removing ghcr reference from ReadMe.MD and this will be merged soon.

Regarding 'image: ghcr.io/catenax-ng/jena-fuseki:4.7.0' , this is the DB used for Semantic-Hub. We are using it to store some aspect model images into it directly. This is our private image from catena-x repo.
