### ISSUE TITLE
chore: add helm upgradeability workflow

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sldt-semantic-hub#165]
This is not a requirement of release 3.2 but will be in the future, you can do it afterwards. Please add the workflow according to the [TRG](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11#description). A good example can be found [here](https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/helm-upgrade.yaml).

**Comment by bs-sili** [comment]
Hi @almadigabor ,
as discussed with the DevSecOps team (@SebastianBezold , @tomaszbarwicki ) this is now not mandatory, but we will take care about it in the future.

**Comment by SebastianBezold** [comment]
Hi @bs-sili,

we are currently preparing the next release and this time the helm upgrade is mandatory. Did you work on it in the meantime? 

This is blocking #190

**Comment by bs-sili** [comment]
Hi @SebastianBezold,
but wasn't this solved the merge of this PR https://github.com/eclipse-tractusx/sldt-semantic-hub/pull/188?

**Comment by SebastianBezold** [comment]
Oh thanks for the reminder @bs-sili, already loosing track of all the issues/repos/fixes 😁 
It's indeed fixed with #188.
Would help me a lot, if PRs are linked to issues they fix (and best also use the auto-closing keywords) in the future

**Comment by bs-sili** [comment]
Same here :-D
Yeah, that we gonna do next time :-)
