### ISSUE TITLE
chore: add Apache 2.0 reference to documentation

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sldt-semantic-hub#166]
Please add a reference to the Apache 2.0 license to the starting point to each of your documentation (for example Arc42, User Guide, Admin Guide) according to this [TRG](https://eclipse-tractusx.github.io/docs/release/trg-0/trg-7-07#documentation).

**Comment by bs-sili** [comment]
Hi @almadigabor ,
the link to the TRG is broken, but I think you meant that one, right? https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07

**Comment by almadigabor** [comment]
Hi @bs-sili! Sorry for the error. You're right, I meant TRG 7.07.

**Comment by bs-sili** [comment]
Hi @almadigabor,
we are not sure about what you mean by "add a reference to the Apache 2.0 license to the starting point". As far as we understood we have to add a Notice section into the documentation.md. This section is already present at the bottom of this file.
Could you provide us an example how it should look like? Many thanks!

**Comment by almadigabor** [comment]
Hi @bs-sili! What you have in the notice section is good enough. Closing this issue.
