### ISSUE TITLE
chore: include FOSS files in the built artifact

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sldt-semantic-hub#167]
You need to include the license, notice and dependencies file in your artifact (not in docker image, but in .jar this case) according to this [TRG](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05#description). You can take a look at [this example](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/consumer-backend/productpass/pom.xml#L189-L202) that already does the same.

- Also don't include these files (License, Notice.md, ...) in the docker image directly via Dockerfile or at lease don't include them in the root as it would indicate that all files in the image are under Apache 2.0 license.

**Comment by tunacicek** [comment]
@almadigabor  On building the jar file, we copy the required files into the jar file (META-INF).
See also:
https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/f00553bd30f46632d2921eccc4a4490a5eecd8e8/backend/pom.xml#L350
