### ISSUE TITLE
TRG 4.02 Using un-altered container base image

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sldt-semantic-hub#191]
The `Dockerfile` present for tag `v0.2.14` (the release version) does use the alpine package manager to upgrade system dependencies. 
These kind of upgrades alter the base container image in a way, that we cannot rely on the published container scans provided by DockerHub. 
Therefore package manager updates/upgrades must not be present in our `Dockerfile`s

See the [upgraded TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) descriptions for a more detailed explanation

**Comment by shijinrajbosch** [comment]
Hi @SebastianBezold,

Thanks for the review comment. We will check the issue.
