### ISSUE TITLE
Adjust Attribution of Catena-X Registry and Semantic Hub APIs

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-semantic-hub#211]
See JIRA ticket 1149 for more details.

As the developer of an open source API I need to do attribution in accordance to the used licenses.

**Comment by thomas-henn** [comment]
As the developer of an open source API I need to do attribution in accordance to the used licenses.

 

Digital Twin Registry:

https://semantics.int.demo.catena-x.net/registry/swagger-ui/index.html

Terms of Service references [https://github.com/admin-shell-io/aas-specs](https://github.com/admin-shell-io/aas-specs.) as stated in https://app.swaggerhub.com/apis/Plattform_i40/Registry-and-Discovery/V1.0RC01 However, in aas-specs the AAS API is not used.

The AAS API is https://creativecommons.org/licenses/by/4.0/

Attribution — You must give [appropriate credit](https://creativecommons.org/licenses/by/4.0/#), provide a link to the license, and [indicate if changes were made](https://creativecommons.org/licenses/by/4.0/#). You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use. 

+

Add information in github repo: https://github.com/eclipse-tractusx/sldt-digital-twin-registry

We do have the documentation of the changes made to the API https://app.swaggerhub.com/apis/Plattform_i40/Registry-and-Discovery/V1.0RC01

 

For semantic Hub there probalby is not attribution needed?

 

Note: In https://app.swaggerhub.com/apis/Plattform_i40/AssetAdministrationShellRegistryServiceSpecification/V3.0_SSP-001 the license information is in

**Comment by thomas-henn** [comment]
https://github.com/eclipse-tractusx/sig-release/issues/347

**Comment by tunacicek** [comment]
The current openApi File includes the required information. 
See here: 
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/main/backend/src/main/resources/static/aas-registry-openapi.yaml
