### ISSUE TITLE
[Blocker] Update aasx file to models in tractusx/sldt-semantic-models repository

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-semantic-hub#214]
Check the parent user story which was done in Iteration #3 >> https://jira.catena-x.net/browse/A1SLDT-1124

Description from US 1124:

"We have generated artifacts int he gen folder for each model in sldt-semantic-models repo. As soon as aas4j supports AASv3.0 a aasx file per model has to be added."

 

depends on https://jira.catena-x.net/browse/A1SLDT-1114

**Comment by shijinrajbosch** [comment]
please refer JIRA userstory the comments section for more details

**Comment by agg3fe** [comment]
This US is on hold for now. We need to wait for new release from AAS4J. Hopefully everything will work with new release.
Else we can regenerate whatever does not work.

**Comment by agg3fe** [comment]
PR for all the changes: https://github.com/eclipse-tractusx/sldt-semantic-models/pull/695
It contains:
1) the samm cli version upgrade from 2.5.1 to 2.6.0
2) Regenerated all the aasx (aasx and aasx.xml) file for all models.
