### ISSUE TITLE
Semantic-hub - HTTP error 400 Bad Request - validation failed

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-semantic-hub#216]
Invalid models (with Validation failed) with ESMF SDK 2.4.2:

4.0.0/BatteryPass.ttl
1.0.0/DeliveryInformation.ttl
3.0.0/DigitalProductPassport.ttl
1.0.0/ItemStock.ttl
1.0.0/MaterialDemand.ttl 
1.0.0/MaterialFlowScenarioRequestAspect.ttl
2.0.0/Pcf.ttl 
1.0.0/QualityTaskAttachment.ttl
1.0.0/GetProductionForecast.ttl 
1.0.0/ProvideProductionForecast.ttl 
2.0.0/SingleLevelBomAsBuilt.ttl
2.0.0/SingleLevelBomAsPlanned.ttl 
2.0.0/SingleLevelUsageAsBuilt.ttl
1.0.0/TimeSeriesReference.ttl 
1.0.0/Waste.ttl
2.0.0/WeekBasedCapacityGroup.ttl 
 

Bad IRI issue for the below models :

1.0.0/DigitalProductPassport.ttl
2.0.0/DigitalProductPassport.ttl
1.0.0/TransmissionPass.ttl

**Comment by thomas-henn** [comment]
https://github.com/eclipse-tractusx/sig-release/issues/347

**Comment by agg3fe** [comment]
https://jira.catena-x.net/browse/A1SLDT-1390

**Comment by agg3fe** [comment]
All the models have been checked again. Only two model out of these have problem.
Issues have been created:
https://github.com/eclipse-tractusx/sldt-semantic-models/issues/598
https://github.com/eclipse-tractusx/sldt-semantic-models/issues/599

**Comment by agg3fe** [comment]
A Github action has been created to upload a single model to semantic-hub incase it is not uploaded during the merge of pull request.
https://github.com/eclipse-tractusx/sldt-semantic-models/actions/workflows/upload-single-model.yml
