### ISSUE TITLE
TRG 5.03 proper version strategy

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/sldt-semantic-hub#244]
https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/03981eba0f6c3e903726b7f009ee6c3c90e74c8a/charts/semantic-hub/README.md?plain=1#L1-L4

Helm Chart Readme contains outdated informations regarding Helm Chart and App Version. This is a non blocking issue in regards of the QG check for release 24.03.

**Comment by tunacicek** [comment]
Updated to the latest version. Issue will be closed.
