### ISSUE TITLE
Add endpoint to GET AAS submodel template as json

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sldt-semantic-hub#56]
As a use case, I want to fetch the SAMM-generated AAS-SMT from the Semantic Hub as AAS-json. For programming languages that have no stack implementing aasx, the format is hard to work with. This relies on https://github.com/eclipse-esmf/esmf-sdk/pull/293.

**Comment by agg3fe** [comment]
Hi,
Thanks for reporting. We are currently working to provide JSON files. Will update you on this.

**Comment by tunacicek** [comment]
SDK is updated. 
It is possible to download json schemas via Semantic-hub. 
Used API is /models/{urn}/json-schema
