### ISSUE TITLE
What is Triplestore, and embeddedTripleStore will use it from where? 

### ISSUE THREAD

**Issue by richaashara** [eclipse-tractusx/sldt-semantic-hub#62]
Hello,
Could someone elaborate on what is Triplestore ? and when to make the property "embeddedTripleStore" true? Other than this embedded what other options are available for it?

**Comment by LuLeRoemer** [comment]
The triplestore is a specific graph database. We use the OS Fuseki triplestore implementation here.
The embeddedTripleStore property used to integrate an in-memory triple store runtime with the Semantic Hub application. However, the support for this feature has been discontinued. Now, you necessarily need to run your own Fuseki instance and configure the Hub to connect to it.
