### ISSUE TITLE
How to poll models from repository sldt-semantic-models

### ISSUE THREAD

**Issue by richaashara** [eclipse-tractusx/sldt-semantic-hub#66]
Hello,

Could someone please let me know, in the semantic hub how can I poll models from the semantic model's repository (https://github.com/eclipse-tractusx/sldt-semantic-models)?  Is there any webhook or any other way is there to sync the semantic hub with the models?

Thanks,
Richa

**Comment by LuLeRoemer** [comment]
We are running a GitHub actions workflow to synchronize the semantic models with an instance of the Hub.

**Comment by richaashara** [comment]
Thank you @LuLeRoemer, I got it.
