### ISSUE TITLE
Improper version management

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sldt-semantic-hub#85]
My understanding is: The semantic hub mirrors the models that are governed in sldt-semantic-models. However, on  https://portal.int.demo.catena-x.net/semantichub/, there are two released versions of MaterialForRecycling.[ sldt-semantic-models](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.material_for_recycling) has no v1.1.0 - still it appears in the semantic hub (see screenshot below)

![image](https://user-images.githubusercontent.com/86715435/229306130-d8a6f9fc-1013-4e42-ac79-02e2aee12a52.png)

**Comment by LuLeRoemer** [comment]
Thanks @arnoweiss for the report. @bs-jokri do you have an idea?

**Comment by shijinrajbosch** [comment]
Hi @arnoweiss , 

We have synchronized the sldt-semantic-models and semantic-hub application.
MaterialForRecycling is showing only version 1.1.0 now
![image](https://github.com/eclipse-tractusx/sldt-semantic-hub/assets/136349699/9fe915bf-3046-4330-8566-8df0c5ff2438)

Please let us know if there are any open issues.

**Comment by arnoweiss** [comment]
Thanks for the fix!
